version: '3'

services:
    etl:
        build: .
        restart: always
        env_file:
          - .env
        depends_on:
          - db
    db:
      image: postgres:15
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=station
      ports:
        - "5444:5432"
      volumes: 
        - .data/:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql